### ISSUE TITLE
Unwanted file ic_launcher.png causing duplicate resource issue [aapt]

### ISSUE THREAD

**Issue by cupadhyay** [citruspay/citrus-android-sdk#1]
Hi Team,

While adding SDK through gradle, facing an aapt resource merge problem.
Duplicate ic_launcher (though its not there in application).

I updated the other library which was having this mistake of having ic_launcher.png to latest version.

But just a suggestion, SDK/Libs should not have such launcher icons as they are of no use. Please remove it from res folder of your SDK.

**Comment by MangeshKadam** [comment]
Hey thanks for pointing this out. Surely it will be fixed in next release. Thanks a ton.

**Comment by cupadhyay** [comment]
Hey Thanks Mangesh, I was using 3.0.36 version, today after you closed the issue I changed the version to 3.1.0. But issue is still open. (I was thinking 3.1.0 was the release you were pointing out as next release today).
If its still open, I would request to reopen the issue for tracking purpose, other user may also face same issue.

**Comment by cupadhyay** [comment]
Its working fine now in 3.1.1 version. Thanks for removing ic_launcher.png.
