### ISSUE TITLE
Signed vs Unsigned APK in LIVE Citrus Environment

### ISSUE THREAD

**Issue by asdec** [citruspay/citrus-android-sdk#12]
The payment gateway works fine in the un-signed Live environment of Citrus. However in signed apk, the Citrus loader keeps on loading on the screen and does not take the user to the Merchant site in all the 3 cases, i.e Credit,Debit and Netbanking. Any changes to be made in proguard file? I am trying to update the SDK.

**Comment by sourabh-verma-citruspay** [comment]
I hope that this issue is resolved already, if isn't please refer to the proguard changes at
https://github.com/citruspay/citrus-android-sdk/blob/master/docs/Progaurd%20changes.md
