### ISSUE TITLE
Images of NetbankingOption and CardOption

### ISSUE THREAD

**Issue by ssatyacc** [citruspay/citrus-android-sdk#13]
I have included the latest SDK and to my surprise there are no images of banks and card schemes.

Looking at the repo, the images might have present in previous versions. I have included version 3.1.1 and it has the images.

Could you please confirm if we should download all the images and include them in project or you would provide them in future version?

**Comment by sourabh-verma-citruspay** [comment]
Hi Satya, We do provide bank & card assets with the sdk. Can you tell us which version of sdk you are trying to upgrade and which method didn't return you the bank or card asset.

**Comment by ssatyacc** [comment]
@sourabh-verma-citruspay I am using the following in my build.gradle

    compile ('com.citrus.sdk:payment-sdk:3.4.8:retrofitnewRelease@aar') {
        transitive = false
    }
I have checked 3.1.1 also, it has the images while the 3.4.8 one doesnot

**Comment by MangeshKadam** [comment]
Hi @ssatyacc ,
please include below dependencies to your build.gradle for icons
 compile 'com.citrus.sdk:bankassets:1.0.0'
    compile 'com.citrus.sdk:cardassets:1.0.0'

**Comment by ssatyacc** [comment]
@MangeshKadam Could you update the same in the docs after which I will close this issue

**Comment by MangeshKadam** [comment]
Updated the doc.
