### ISSUE TITLE
I am getting this error

### ISSUE THREAD

**Issue by narendrakothamire** [citruspay/citrus-android-sdk#14]
Gradle sync failed: Could not find com.citrus.sdk:payment-sdk:3.4.3.

**Comment by Mangesh21** [comment]
@narendrakothamire  - use 3.4.8 version. Thats the latest one.

**Comment by Vaibhavandroid** [comment]
Error:(46, 13) Failed to resolve: com.citrus.sdk:payment-sdk:3.4.8

**Comment by MangeshKadam** [comment]
update your top level gradle file with  maven { url "http://dl.bintray.com/developer/maven" }
You can check doc at https://github.com/citruspay/citrus-android-sdk
