### ISSUE TITLE
Getting crash on client.PGClient.makeMOTOPayment

### ISSUE THREAD

**Issue by visareshwar** [citruspay/citrus-android-sdk#15]
Hi,
We are getting crash during payment. Here is the log. Please have a look.

[log.txt](https://github.com/citruspay/citrus-android-sdk/files/319780/log.txt)

**Comment by MangeshKadam** [comment]
@visareshwar  - could you please also share the piece of code?

**Comment by visareshwar** [comment]
// Payment Mode : PAYMENT_MODE_CITRUS
    @Override
    public void onCirtusPayInitiated(PaymentOption paymentOption) {
        NestLog.d(TAG, "onCirtusPayInitiated(" + paymentOption + ")");
        CitrusClient client = CitrusClient.getInstance(this);
        PaymentType paymentType;
        try {
            paymentType = new PaymentType.PGPayment(mCitrusBill, paymentOption,
                    new CitrusUser(mEmail, mPhone));
            client.pgPayment((PaymentType.PGPayment) paymentType, new CitrusCallBack());
        } catch (CitrusException | JSONException e) {
            e.printStackTrace();
        }
    }

**Comment by visareshwar** [comment]
Heyy!! Any update on this issue. We are getting 2-3 crashes everyday.

**Comment by MangeshKadam** [comment]
@visareshwar  - are you trying to do saved Card Payment or new card payment? From the logs I can see some of the required parameters for API to execute successfully are missing.

**Comment by visareshwar** [comment]
We are using new card. Can you please let me know what all parameter we are missing.

**Comment by MangeshKadam** [comment]
@visareshwar  - you can check the doc at
https://github.com/citruspay/citrus-android-sdk/blob/master/docs/CC%20%2CDC%20%2CNB%20Direct%20Payment.md

**Comment by visareshwar** [comment]
looks no difference to me. Here is my code 

             PaymentOption paymentOption = null;
               if (mIsDebitCard) {
                    paymentOption = new DebitCardOption(name, number, cvv, month, year);
                } else if (mIsCreditCard){
                    paymentOption = new CreditCardOption(name, number, cvv, month, year);
                }else if (mIsNetbanking){
                    paymentOption = new NetbankingOption(mBankName, mBankCID);
                } 
             if(paymentOption!=null){
              onCirtusPayInitiated(paymentOption);
             }

**Comment by MangeshKadam** [comment]
Code looks fine. Could you please tell me if its issue with card or netbanking?

**Comment by visareshwar** [comment]
I am not sure. We have released the app. So it can be card or netbanking, 
Its sometimes issue.

**Comment by visareshwar** [comment]
@MangeshKadam !! any update on this issue?

**Comment by Pratima-Gadekar** [comment]
will give you an update soon. checking on our end.

**Comment by Pratima-Gadekar** [comment]
@visareshwar can you share the name of your app so that we can test on our end where the application is crashing?

**Comment by visareshwar** [comment]
**Nestaway** (com.nestaway.customerapp)

**Comment by Pratima-Gadekar** [comment]
@visareshwar  Could you please ask your development team to test the app and let us know if its a netbanking or card issue. Not able t debug on our end.
