### ISSUE TITLE
Multidex files defined issue for Google Play Service 

### ISSUE THREAD

**Issue by cupadhyay** [citruspay/citrus-android-sdk#2]
Hi Team, 
I have included the Citrus SDK via Gradle. In my project I was already having dependency of Google Play service. As we know Citrus SDK has included GMS lib too, because of version mismatch of multiple jar/dex developer may get multidex file defined issue, like -

```
android gradle Multiple dex files define Lcom/google/android/gms/internal/zzlv
```

Please mention a note in [Readme] (../blob/master/README.md) for such cases where Apps are having dependency of GMS and getting this multidex problem, please use below convention in build.gradle -

```
compile ('com.citrus.sdk:payment-sdk:3.1.1') {
    transitive = false
}
```
I hope this will solve the problem.

*Regards,
Chetan*

**Comment by MangeshKadam** [comment]
Hey Chetan, thanks for pointing this out. Surely we will update in our readme doc.
