### ISSUE TITLE
Payment options are not displayed in production

### ISSUE THREAD

**Issue by AlexSheiko** [citruspay/citrus-android-sdk#20]
Hello, @MangeshKadam.

In production mode, when I'm saving a payment option `citrusClient.savePaymentOption(creditCard, callback)`, the callback triggers success method.

But when I'm querying for this payment option later, `citrusClient.getWallet(callback)`, I can see that it actually wasn't saved: *{"type":"payment","defaultOption":"","paymentOptions":[]}*

On the other hand, saved options are returned correctly in the test mode.

**Comment by MangeshKadam** [comment]
Hi @AlexeySheiko  - could you please share the logs? Logs will help us to resolve the problem quickly.
Please share logs to mangesh.kadam@citruspay.com

**Comment by salilgodbole** [comment]
Hi @AlexeySheiko,
Also let us know which card you are trying to save i.e. VISA or MASTERCARD or other.
The card might be getting saved correctly but the card scheme may not be available for you on production.

Please provide details so that we can investigate this.

**Comment by AlexeySheiko** [comment]
Hi, @salilgodbole. I'm using a debit Visa card, issued in Poland. There's also a person who uses an _Indian_ MasterCard, and he has the same problem.

You're right that the cards are saved correctly, because I'm getting a successful response after saving it. 

And to retrieve it later, could you tell me which cards are supported in production? Perhaps only from India, and only Visa?

**Comment by AlexeySheiko** [comment]
@MangeshKadam, here are the logs, and you'll find the version with uncommented Authorization token in your inbox.

The card used in this example is an Indian credit MasterCard.

---> HTTP PUT https://admin.citruspay.com/service/v2/profile/me/payment
Authorization: Bearer 20881d62-5229-4b71-8408-790aa6e2XXXX
{"paymentOptions":[{"owner":"XXXXXX X XXXXXXXX","number":"53XXXXXXXXXXXXXX","scheme":"MASTER_CARD","expiryDate":"01\/2021","type":"credit"}],"type":"payment"}
<--- HTTP 204 https://admin.citruspay.com/service/v2/profile/me/payment

---> HTTP GET https://admin.citruspay.com/service/v2/profile/me/payment
Authorization: Bearer 20881d62-5229-4b71-8408-790aa6e2XXXX
<--- HTTP 200 https://admin.citruspay.com/service/v2/profile/me/payment
{"type":"payment","defaultOption":"","paymentOptions":[]}

**Comment by MangeshKadam** [comment]
@AlexeySheiko  - after debugging the issue, problem seems with the token. Seems like few of the scopes are missing for the keys. Request you share keys used in prod environment along-with all the logs from signin. Please share the logs on email , it contains sensitive data.

**Comment by AlexeySheiko** [comment]
@MangeshKadam, I've sent you my production keys, and will add signin logs later as well.
