### ISSUE TITLE
After successfully recharging the citrus wallet its showing html code.

### ISSUE THREAD

**Issue by swatisoni29** [citruspay/citrus-android-sdk#21]
After successfully recharging the citrus wallet its showing me html code. But amount is credited in my wallet. After recharging the wallet its not redirect to home screen. In both the environment we are facing this issue.

Th HTML code is as follows:

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Redirect URL</title>
<script type="text/javascript">
	function postResponse(data) {
		document.write(data);
		  CitrusResponse.loadWalletResponse(data);
	}
		var url = window.location.href;
		var index = url.indexOf("#");
		if(index != -1){
			var queryString = url.substring(index + 1);				
			postResponse("#"+queryString);
		}			
</script>
</head>
<body>
</body>
</html>

**Comment by MangeshKadam** [comment]
This is because your redirectURL page could not communicate with SDK via jsinterface. If this communication is successful, SDK will close the webview and response will be returned to the app.
Please refer https://developers.citruspay.com/doc/integrations/  for returnURL page code.
