### ISSUE TITLE
Runtime Exception NoClassDefFoundError Logger - com/orhanobut/logger/Logger

### ISSUE THREAD

**Issue by cupadhyay** [citruspay/citrus-android-sdk#3]
Now Getting NoClassDefFoundError - 
```
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/orhanobut/logger/Logger;
            at com.citrus.sdk.response.CitrusLogger.enableLogs(CitrusLogger.java:16)
            at com.citrus.sdk.CitrusClient.enableLog(CitrusClient.java:164)
```
INFO: Gradle mode, Version: 3.1.1

I guess SDK missed [Logger Lib] (https://github.com/orhanobut/logger)

**Comment by somnathpzalte** [comment]
I'm facing same problem

**Comment by MangeshKadam** [comment]
@somnathpzalte  - we have fixed this issue in our latest SDK version. Latest SDK version is 3.4.11. Also follow the below link for more details
https://github.com/citruspay/citrus-android-sdk

**Comment by somnathpzalte** [comment]
Thnx MangeshKadam
