### ISSUE TITLE
Upgrading to Retrofit 2

### ISSUE THREAD

**Issue by themouli** [citruspay/citrus-android-sdk#4]
I am using retrofit 2 in my app. So, is there any way i can port this to retrofit 2?

**Comment by MangeshKadam** [comment]
Hi,
we have beta version ready for retrofit 2.0. If you would like to give try, I can help you out.

**Comment by themouli** [comment]
ya, just noticed that. Thanks

**Comment by MangeshKadam** [comment]
No. API will be same only. Response returned from SDK will also be same. Internal implementation will be based on retrofit 2.0. We have aar file ready to use. Just drop a mail to mobiledev@citruspay.com

**Comment by muditjaju** [comment]
Getting a similar error .. I am also using Retrofit 2.0 in my project. Is this because of the same reason ?
```
FATAL EXCEPTION: main
Process: in.infiniteeurekas.cherishtest, PID: 28996
java.lang.NoClassDefFoundError: com.citrus.retrofit.CitrusEndPoint
at com.citrus.retrofit.RetroFitClient.setupCitrusRetroFitClient(RetroFitClient.java:35)
at com.citrus.retrofit.RetroFitClient.initRetroFitClient(RetroFitClient.java:31)
```

**Comment by MangeshKadam** [comment]
yes.. surely this bug is because of retrofit 2.0 and retrofit 1.9 conflicts.  We will update github doc and provide you the retrofit 2.0 by tomorrow EOD. Thanks.

**Comment by muditjaju** [comment]
@MangeshKadam  - Thanks for the followup. 
But I did look at the retrofit library and in their beta3 version they have updated the namespace to retrofit2 and hence I added both the 2.0.0beta3 and the 1.9 libraries in my project together.
But still getting the same error :|

**Comment by MangeshKadam** [comment]
@muditjaju  - this is not issue with retrofit. Citrus SDK was developed  with retrofit 1.9  version. Your app is using retrofit 2.0 version and the latest retrofit 2.0 version is not backward compatible. So problem is your app using 2.0 and citrus SDK is using 1.9 version. We have updated citrus SDK with retrofit 2.0 version. We will provide this new SDK by tomorrow EOD.

**Comment by salilgodbole** [comment]
Hi Mudit,

We have updated Citrus SDK with support to retrofit 2.0.
Please follow following steps to import the Citrus SDK in your app.

// Add Citrus SDK
compile  'com.citrus.sdk:payment-sdk:3.1.8:retrofitnewRelease@aar'

// Citrus SDK uses some additional dependencies internally. You need to add these dependencies in your app's build.gradle file.
// citrus sdk dependencies for retrofit
// For retrofit version 2.0
    compile('com.squareup.retrofit:retrofit:2.0.0-beta2') {
        // exclude Retrofit’s OkHttp peer-dependency module and define your own module import
        exclude module: 'okhttp'
    }
    compile 'com.squareup.okhttp:okhttp:2.5.0'
    compile 'com.squareup.retrofit:converter-gson:2.0.0-beta2'
    compile 'com.squareup.okhttp:logging-interceptor:2.6.0' //to enable logging
// Other retrofit dependencies.
    compile 'com.squareup.okhttp:okhttp:2.3.0'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.3.0'
    compile 'com.squareup.okio:okio:1.3.0'
    compile 'com.orhanobut:logger:1.8'

//
    compile 'com.google.android.gms:play-services-analytics:7.8.0'
    compile 'com.android.support:appcompat-v7:23.1.0'
    compile 'de.greenrobot:eventbus:2.4.0'
    compile "com.facebook.conceal:conceal:1.0.1@aar"

You may only add missing dependencies from your apps' build.gradle.
