### ISSUE TITLE
java.lang.NoClassDefFoundError: com.citrus.retrofit.CitrusEndPoint

### ISSUE THREAD

**Issue by Aakarshrai1** [citruspay/citrus-android-sdk#8]
**my code is
import java.util.ArrayList;

import com.citrus.sdk.Callback;
import com.citrus.sdk.CitrusClient;
import com.citrus.sdk.payment.MerchantPaymentOption;
import com.citrus.sdk.payment.NetbankingOption;
import com.citrus.sdk.response.CitrusError;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import android.widget.EditText;
import android.widget.RadioButton;

public class MainActivity extends Activity {

	String Mode, Amount;
	RadioButton DebitCard, CreditCard, NetBanking;
	EditText etAmount;
	Button btnProceed;

	CitrusClient citrusClient;
	String EmailID = "developercitrus@gmail.com";
	String MobileNo = "9876543210";

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		// TODO Auto-generated method stub
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);

		citrusClient = CitrusClient.getInstance(this);
		citrusClient.init(Constants.SIGNUP_ID, Constants.SIGNUP_SECRET, Constants.SIGNIN_ID, Constants.SIGNIN_SECRET,
				Constants.VANITY, Constants.environment);
		;
		init();

		btnProceed = (Button) findViewById(R.id.btnProceed);
		btnProceed.setOnClickListener(new OnClickListener() {

			@Override
			public void onClick(View v) {
				// TODO Auto-generated method stub
				Intent intent = new Intent(MainActivity.this, UIActivity.class);

				Amount = etAmount.getText().toString();
				if (DebitCard.isChecked())
					Mode = "DebitCard";

				else if (CreditCard.isChecked())
					Mode = "CreditCard";

				else if (NetBanking.isChecked())
					Mode = "NetBanking";

				intent.putExtra(Amount, "Amount");
				intent.putExtra(Mode, "Mode");

				startActivity(intent);

			}
		});

	}

	private void init() {
		// TODO Auto-generated method stub

		etAmount = (EditText) findViewById(R.id.etRuppess);
		CreditCard = (RadioButton) findViewById(R.id.rb_Credit);
		DebitCard = (RadioButton) findViewById(R.id.rb_Debit);
		NetBanking = (RadioButton) findViewById(R.id.rb_NetBank);

	}

	void getMerchantOptions() {
		citrusClient.getMerchantPaymentOptions(new Callback<MerchantPaymentOption>() {

			@Override
			public void success(MerchantPaymentOption merchantPaymentoption) {
				// TODO Auto-generated method stub
				ArrayList<NetbankingOption> mNetbankingOptionsList = merchantPaymentoption.getNetbankingOptionList();
				for (NetbankingOption b : mNetbankingOptionsList) {
					Log.d("tagg", b.getBankName());
				}

			}

			@Override
			public void error(CitrusError arg0) {
				// TODO Auto-generated method stub

			}
		});
	}

}
**

**Comment by Aakarshrai1** [comment]
i m frustrated to solve this execption plz help me

**Comment by MangeshKadam** [comment]
@Aakarshrai1  - please use our latest version of SDK. I think you are using old SDK version. Have a look at https://github.com/citruspay/citrus-android-sdk
Let me know if it helps as latest version of SDK has this bug fixed.
